### PR TITLE
One function has been moved from cart_summary.py to cart.py

### PR DESCRIPTION
**Pull request by Wojciech-Wawrzyszko**
Function 'normalize_string' has been moved from cart_summary.py to cart.py.

### CODE REVIEW

**Comment by PawelEnerlich** [comment]
This function is still in the cart_summary.py. I think you have to delete it there.

**Comment by Wojciech-Wawrzyszko** [comment]
Function 'normalize_string' has been deleted from cart_summary.py (now it is in cart.py).

**Comment by PawelEnerlich** [comment]
There is no import in cart_summary.py for normailze_string method.

**Comment by Wojciech-Wawrzyszko** [comment]
3 files have been updated because of errors:
 - cart.py
 - cart_summary.py
 - mod_loyalty.py

**Review by PawelEnerlich — COMMENTED** [review]
The issue has been resolved.

**Pull request merged**
